# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

VM_NAME = "macos-#{File.basename(Dir.getwd)}-base"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vagrant.plugins = ["vagrant-reload", "vagrant-disksize"]

  config.vm.box = "nick-invision/macos-monterey-vanilla"
  # config.vm.box_version = "0.0.2"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 3600 # 60m

  config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"
  # config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.disksize.size = '80GB'

  config.vm.provider "parallels" do |v|
    v.name = VM_NAME
    v.memory = 8192
    v.cpus = 2
  end

  # manually run
  config.vm.provision "setup", 
    type: "shell", 
    privileged: false,
    run: 'never', 
    path: "../scripts/configure-base-box.sh"
end
